# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 邪恶二进制
email: 597369804@qq.com
description: > # this means to ignore newlines until "baseurl:"
   码农<br>
   互联网后台<br>
   Linux C++<br>
   坐标深圳
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zxlchina.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  zxlchina 
qq_number:  597369804

# Build settings
markdown: kramdown
